---
galaxy_info:
  author: wzzrd
  description: Install and enable Apache httpd
  license: GPL-2.0-or-later
  min_ansible_version: "2.17"
  platforms:
    - name: EL
      versions:
        - all

dependencies: []
